org: tvqqq
app: profile-counter
service: profile-counter
frameworkVersion: "3"
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  timeout: 30
  environment:
    DDB_TABLE_NAME: ${param:DDB_TABLE_NAME}

plugins:
  - serverless-iam-roles-per-function

functions:
  api:
    handler: handler.serverless
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:*
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DDB_TABLE_NAME}"
    events:
      - httpApi: "*"
